{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <unit.test_pytest.TestClass object at 0x000001EA98791580>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nunit\\test_pytest.py:36: AssertionError"}, "attachments": [{"name": "stdout", "source": "dd97fa30-39b6-41ad-8530-5728e0c5f2a5-attachment.txt", "type": "text/plain"}], "start": 1583118100932, "stop": 1583118100933, "uuid": "18280388-d727-405c-b6c9-391de339f2ad", "historyId": "f29c6df3a2c6e467cf125441fc92b055", "testCaseId": "89fea8c6fc1c84d5ebed1bc186c1df83", "fullName": "unit.test_pytest.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-2P3JG1L"}, {"name": "thread", "value": "6744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_pytest"}]}